# Generated by Django 5.0.7 on 2024-08-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='auther',
            new_name='author',
        ),
    ]
